# Generated by Django 3.2.6 on 2021-08-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dryingredient",
            options={},
        ),
        migrations.AlterModelOptions(
            name="fatingredient",
            options={},
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={},
        ),
        migrations.AlterModelOptions(
            name="wetingredient",
            options={},
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="created",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="description",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="title",
        ),
    ]
