# Generated by Django 3.2.6 on 2021-08-24 23:53

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                ("mixing_notes", models.TextField()),
                ("room_temperature", models.IntegerField()),
                ("flour_temperature", models.IntegerField()),
                ("liquid_temperature", models.IntegerField()),
                ("total_first_speed_mixing_time", models.DurationField()),
                ("total_second_speed_mixing_time", models.DurationField()),
                ("temperature_before_fermentation", models.IntegerField()),
                ("fermentation_time", models.DurationField()),
                ("temperature_after_fermentation", models.IntegerField()),
                ("first_fermentation_volume_increase", models.IntegerField()),
                (
                    "recipe_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.recipeversion",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
