# Generated by Django 3.2.6 on 2021-08-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batches", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={},
        ),
    ]
